db.url=jdbc:postgresql://postgres_cards:5432/cardsdb
db.user=postgres
db.password=postgres
db.driver.classname=org.postgresql.Driver
feign.getAccountsUrl=http://accounts:8081
feign.getAccountsUrl.username=user
feign.getAccountsUrl.password=user123