db.url=jdbc:postgresql://postgres_cards:5432/cardsdb
db.user=postgres
db.password=postgres
db.driver.classname=org.postgresql.Driver
feign.accounts.url=http://accounts:8081
feign.accounts.username=user
feign.accounts.password=user123